name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 1) Поднимаем контейнер БД из docker-compose.yml
      - name: Container start
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: docker-compose.yml

      # 2) Ждём запуска контейнера
      - name: Waiting for container start
        run: sleep 30

      # 3) Запускаем SUT в фоне
      - name: Run SUT
        run: |
          java -jar artifacts/app-deadline.jar &

      # (необязательно, но часто спасает от гонок)
      - name: Waiting for SUT start
        run: sleep 10

      # 4) Запускаем тесты
      - name: Build with Gradle
        run: ./gradlew test -Dselenide.headless=true --info